const DATABASE = `CREATE DATABASE nodejs_shop;`;

const TABLE_PRODUCTS = `CREATE OR REPLACE TABLE nodejs_shop.product (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  price DOUBLE NOT NULL,
  imageUrl VARCHAR(255) NOT NULL,
  description TEXT NOT NULL
);`;

const INDEX_PRODUCTS = `CREATE OR REPLACE UNIQUE INDEX id_UNIQUE ON nodejs_shop.product(id ASC);`;
